import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminUsersRouter from "./admin-users";
import prayerRouter from "./prayer";
import announcementsRouter from "./announcements";
import eventsRouter from "./events";
import coursesRouter from "./courses";
import donationsRouter from "./donations";
import galleryRouter from "./gallery";
import servicesRouter from "./services";
import enquiriesRouter from "./enquiries";
import volunteersRouter from "./volunteers";
import staffRouter from "./staff";
import newsRouter from "./news";
import settingsRouter from "./settings";
import storageRouter from "./storage";
import notificationRecipientsRouter from "./notification-recipients";
import membersRouter from "./members";
import quranRouter from "./quran";
import supportRouter from "./support";
import blogRouter from "./blog";
import deviceTokensRouter from "./device-tokens";
import pushNotificationsRouter from "./push-notifications";
import googleMapsRouter from "./google-maps";
import emailCampaignsRouter from "./email-campaigns";
import seedBlogsRouter from "./seed-blogs";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(adminUsersRouter);
router.use(prayerRouter);
router.use(announcementsRouter);
router.use(eventsRouter);
router.use(coursesRouter);
router.use(donationsRouter);
router.use(galleryRouter);
router.use(servicesRouter);
router.use(enquiriesRouter);
router.use(volunteersRouter);
router.use(staffRouter);
router.use(newsRouter);
router.use(settingsRouter);
router.use(storageRouter);
router.use(notificationRecipientsRouter);
router.use(membersRouter);
router.use(quranRouter);
router.use(supportRouter);
router.use(blogRouter);
router.use(deviceTokensRouter);
router.use(pushNotificationsRouter);
router.use(googleMapsRouter);
router.use(emailCampaignsRouter);
router.use(seedBlogsRouter);

export default router;
